<?php

/**
 * Implements hook_views_api().
 */
function views_fields_onoff_views_api() {
  return array(
      'api' => 3,
      'path' => drupal_get_path('module', 'views_fields_onoff') . '/includes/views',
  );
}

/**
 * Implements hook_views_pre_view().
 * @param $view
 * @param $display_id
 * @param $args
 */
function views_fields_onoff_views_pre_view(&$view, &$display_id, &$args) {
  // Grab the fields_onoff values that have been submitted already
  $checked_fields = array_key_exists('fields_onoff', $_GET) ? $_GET['fields_onoff'] : array();
  if (count($checked_fields)) {
    foreach ($view->display_handler->default_display->options['fields'] as $key => $field) {
      if (!array_key_exists($key, $checked_fields)) {
        // If there are fields specified, and this field is one of them, hide it!
        $view->display_handler->default_display->options['fields'][$key]['exclude'] = 1;
      }
    }
  }
}

